language: node_js
sudo: true
services:
- docker
node_js:
- 10
before_install:
- openssl aes-256-cbc -K $encrypted_b020f84874da_key -iv $encrypted_b020f84874da_iv
  -in secrets.zip.enc -out secrets.zip -d
- unzip secrets.zip
install:
- npm install
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
script:
- npm run build
- docker build . --tag=eu.gcr.io/kube-personal/robin-dot-com:latest
- docker login -u _json_key -p "$(cat terraform/account.json)" eu.gcr.io
- docker push eu.gcr.io/kube-personal/robin-dot-com:latest
