apiVersion: v1
kind: ServiceAccount
metadata:
  name: travis
  namespace: robin
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: robin
  name: travis-deploy-role
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["extensions", "apps"]
  resources: ["ingresses"]
  verbs: ["get", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: travis-role-binding
  namespace: robin
subjects:
- kind: ServiceAccount
  name: travis
  namespace: robin
roleRef:
  kind: Role
  name: travis-deploy-role
  apiGroup: rbac.authorization.k8s.io